### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.FuncParser#34]
[AddRef.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/4230638/AddRef.zip)
Right click on the empty area of the formulas in Events-BB and select `Create Reference...`
MoBi v9 crashes completely without any error message.

In the windows error log: 
<details><summary>Error</summary>

```
Application: MoBi.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OSPSuite.FuncParser.ParsedFunctionImports.SetVariableNames(IntPtr, System.String[], Int32)
   at OSPSuite.FuncParser.ParsedFunction.SetVariableNames(System.Collections.Generic.IEnumerable`1<System.String>)
   at OSPSuite.Core.Services.ExplicitFormulaParser..ctor(System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<System.String>, OSPSuite.FuncParser.ParsedFunction)
   at OSPSuite.Core.Services.ExplicitFormulaParser..ctor(System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<System.String>)
   at OSPSuite.Core.Domain.Formulas.FormulaWithFormulaString+<>c.<.cctor>b__15_0(System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<System.String>)
   at OSPSuite.Core.Domain.Formulas.FormulaWithFormulaString.Validate(System.String)
   at OSPSuite.Core.Domain.Formulas.FormulaWithFormulaString.IsValid(System.String)
   at MoBi.Presentation.Tasks.MoBiFormulaTask.Validate(System.String, OSPSuite.Core.Domain.Formulas.FormulaWithFormulaString, OSPSuite.Core.Domain.Builder.IBuildingBlock)
   at MoBi.Presentation.Presenter.EditExplicitFormulaPresenter.Validate(System.String)
   at MoBi.Presentation.Presenter.EditExplicitFormulaPresenter.Edit(OSPSuite.Core.Domain.Formulas.ExplicitFormula)
   at MoBi.Presentation.Presenter.BasePresenter.AbstractEditPresenter`3[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Edit(System.Object)
   at MoBi.Presentation.Presenter.EditTypedFormulaPresenter`3[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Edit(OSPSuite.Core.Domain.Formulas.IFormula, OSPSuite.Core.Domain.IEntity)
   at MoBi.Presentation.Presenter.EditExplicitFormulaPresenter.Edit(OSPSuite.Core.Domain.Formulas.IFormula, OSPSuite.Core.Domain.IEntity)
   at MoBi.Presentation.Presenter.FormulaCachePresenter.Select(OSPSuite.Core.Domain.Formulas.IFormula)
   at MoBi.Presentation.Presenter.FormulaCachePresenter.Handle(MoBi.Core.Events.FormulaChangedEvent)
   at OSPSuite.Utility.Events.EventPublisher+<>c__DisplayClass4_1`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(System.Action)
   at OSPSuite.Utility.Events.EventPublisher+<>c__DisplayClass4_1`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<PublishEvent>b__0(System.Object)

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(System.Object)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   at System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Send(System.Threading.SendOrPostCallback, System.Object)
   at OSPSuite.Utility.Events.EventPublisher.PublishEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon)
   at MoBi.Core.Domain.Model.MoBiContext.PublishEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon)
   at MoBi.Core.Commands.AddFormulaUsablePathCommand.ExecuteWith(MoBi.Core.Domain.Model.IMoBiContext)
   at OSPSuite.Core.Commands.OSPSuiteCommand`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Execute(System.__Canon)
   at OSPSuite.Core.Commands.Core.CommandExtensions.Run[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, System.__Canon)
   at MoBi.Presentation.Tasks.MoBiFormulaTask.AddFormulaUsablePath(OSPSuite.Core.Domain.Formulas.IFormula, OSPSuite.Core.Domain.IFormulaUsablePath, OSPSuite.Core.Domain.Builder.IBuildingBlock)
   at MoBi.Presentation.Presenter.EditFormulaPathListPresenter.AddPathToFormula(OSPSuite.Core.Domain.IFormulaUsablePath)
   at MoBi.Presentation.Presenter.EditFormulaPathListPresenter.CreateNewPath()
   at OSPSuite.Presentation.MenuAndBars.ExecuteActionUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(OSPSuite.Presentation.MenuAndBars.IUICommand, OSPSuite.Utility.Events.IEventPublisher, OSPSuite.Core.Services.IChangePropagator)
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(OSPSuite.Presentation.MenuAndBars.IUICommand)
   at OSPSuite.Presentation.MenuAndBars.MenuBarButton.Click()
   at OSPSuite.UI.Mappers.MenuBarButtonToBarItemMapperBase+<>c__DisplayClass1_0.<UpdateBarButtonItem>b__0(System.Object, DevExpress.XtraBars.ItemClickEventArgs)
   at DevExpress.XtraBars.BarItem.OnClick(DevExpress.XtraBars.BarItemLink)
   at DevExpress.XtraBars.BarButtonItem.OnClick(DevExpress.XtraBars.BarItemLink)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(DevExpress.XtraBars.BarLinkAction, System.Object)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(DevExpress.XtraBars.BarItemLink)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(DevExpress.XtraBars.BarItemLink)
   at DevExpress.XtraBars.Controls.CustomLinksControl.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.Control.WmMouseUp(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at DevExpress.XtraBars.Controls.CustomControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at MoBi.UI.Services.MoBiApplication.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(System.String[])
   at MoBi.Program.Main(System.String[])
```
</details>

![grafik](https://user-images.githubusercontent.com/25061876/74933101-9a527c00-53e3-11ea-8eb2-f8a3aa4a0886.png)

**Comment by msevestre** [comment]
WOW
